steps:
  # Backend (.NET)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bdfy-backend', '-f', './Dockerfile', '.']
    dir: 'app/Bdfy'

  # Frontend (Node)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bdfy-frontend', '-f', './Dockerfile', '.']
    dir: 'app/BDfy-Frontend'

images:
  - 'gcr.io/$PROJECT_ID/bdfy-backend'
  - 'gcr.io/$PROJECT_ID/bdfy-frontend'
