steps:
  # Build de imagen para el backend (C# / .NET)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bdfy-backend', '-f', 'app/Bdfy/Dockerfile', '.']

  # Build de imagen para el frontend (Node.js / React)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bdfy-frontend', '-f', 'app/BDfy-Frontend/Dockerfile', '.']

images:
  - 'gcr.io/$PROJECT_ID/bdfy-backend'
  - 'gcr.io/$PROJECT_ID/bdfy-frontend'
