services:
  backend:
    build:
      context: ./app/Bdfy
      dockerfile: Dockerfile
    ports:
      - "5015:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=BDfyDatabase;Username=root;Password=1234
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - db
      - rabbitmq
    networks:
      - bidify-net

  frontend:
    build:
      context: ./app/BDfy-Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - backend
    networks:
      - bidify-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: BDfyDatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/Bdfy/Data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bidify-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - bidify-net

volumes:
  pgdata:

networks:
  bidify-net:
