services:
  backend:
    build:
      context: ./app/Bdfy
      dockerfile: Dockerfile
    ports:
      - "5015:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=BDfyDatabase;Username=root;Password=1234
      - RabbitMQ__HostName=albatross.rmq.cloudamqp.com
      - RabbitMQ__UserName=gozumern
      - RabbitMQ__Password=33BzwUJ4495rZmj93D_a2vOlQ0fb6las
      - RabbitMQ__VirtualHost=gozumern
      - RabbitMQ__UseSsl=true
      - RabbitMQ__Port=5671
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - bidify-net

  frontend:
    build:
      context: ./app/BDfy-Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - backend
    networks:
      - bidify-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: BDfyDatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/Bdfy/Data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bidify-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d BDfyDatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  bidify-net: