steps:
  # Solo Backend (.NET)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/directed-potion-461814-a6/bdfy-backend', '-f', './Dockerfile', '.']
    dir: 'app/Bdfy'

images:
  - 'gcr.io/directed-potion-461814-a6/bdfy-backend'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100