name: Build y Test BDfy
on:
  push:
    branches:
      - main
      - main-dev
      - test-actions
  pull_request:
    branches:
      - main
      - main-dev
      - test-actions

jobs:
  backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./app/Bdfy/Bdfy.csproj
      - name: Build
        run: dotnet build --no-restore ./app/Bdfy/Bdfy.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal ./app/Bdfy/Bdfy.csproj

  frontend:
    name: Build & Test React Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd app/BDfy-Frontend
          npm ci
      - name: Build
        run: |
          cd app/BDfy-Frontend
          npm run build
      - name: Test
        run: |
          cd app/BDfy-Frontend
          npm test -- --watchAll=false || true

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build backend Docker image
        run: docker build -t bdfy-backend ./app/Bdfy
      - name: Build frontend Docker image
        run: docker build -t bdfy-frontend ./app/BDfy-Frontend
